name = "ThermoCycleGlides"
uuid = "58ad84e6-b92d-4139-8d7e-462257ec6cf0"
version = "0.2.9"
authors = ["Sushrut"]

[deps]
Clapeyron = "7c7805af-46cc-48c9-995b-ed0ed2dc909a"
FiniteDifferences = "26cc04aa-876d-5657-8c51-4c34ba976000"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
Metaheuristics = "bcdb8e00-2c21-11e9-3065-2b553b22f898"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
Clapeyron = "0.6.19"
FiniteDifferences = "0.12.32"
ForwardDiff = "0.10,1"
Interpolations = "0.16.1"
Metaheuristics = "3.4.0"
Polynomials = "4.1.0"
Preferences = "1.5.0"
RecipesBase = "1.3.4"
StaticArrays = "1.9.15"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
